version: '2'
services:
  mailman:
    image: fauria/mailman
    restart: always
    hostname: list.coala.io
    ports:
      - "25:25"
    env_file: .secrets
    environment:
      - URL_FQDN=list.coala.io
      - EMAIL_FQDN=list.coala.io
    networks:
      - outside
networks:
  outside:
    external: true
