version: '2'
services:
  murmur:
    image: bddenhartog/alpine-murmur:2.3.3
    restart: always
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - ./welcome.txt:/data/welcome.txt
