version: '2'
services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    networks:
      - outside
networks:
  outside:
    external: true
