version: '3'
services:
  http:
    image: nginx
    restart: always
    volumes:
      - ./nginx.http.conf:/etc/nginx/nginx.conf:ro
      - cert-volume:/tmp/letsencrypt:ro
    ports:
      - 80:80
  https:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf.d:/etc/nginx/conf.d:ro
      - ./nginx.common.conf:/etc/nginx/nginx.common.conf:ro
      - cert-volume:/etc/letsencrypt:ro
    ports:
      - 443:443
    environment:
      - LE_RENEW_HOOK=docker kill -s HUP @CONTAINER_NAME@
    networks:
      - outside
  le:
    image: kvaps/letsencrypt-webroot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cert-volume:/etc/letsencrypt
      - cert-volume:/tmp/letsencrypt
    links:
      - https
    environment:
      - DOMAINS=coala.io www.coala.io blog.coala.io list.coala.io mumble.coala.io webservices.coala.io solar.coala.io 
      - EMAIL=yukinagato@protonmail.com
      - WEBROOT_PATH=/tmp/letsencrypt
      - EXP_LIMIT=30
      - CHECK_FREQ=30
networks:
  outside:
    external: true
volumes:
  cert-volume:
